// Basic types to resolve TypeScript errors

// Database types (will be auto-generated by Supabase)
declare global {
  type Database = any;
}

// Basic interfaces for the application
export type AuthProvider = 'google' | 'github' | 'email';

export interface AuthProviderConfig {
  id: AuthProvider;
  name: string;
  icon?: string;
}

export interface Table {
  id: string;
  name: string;
}

export interface AppSupabaseClient {
  from: (table: string) => any;
  channel: (name: string) => any;
  removeChannel: (channel: any) => any;
}

// Org chart types
export interface OrgMemberNodeData {
  user: {
    id: string;
    username: string;
    display_name: string;
    avatar_url?: string;
  };
  role: string;
  department: string;
  departmentColor: string;
}

export interface OrgMemberNode {
  id: string;
  position: {
    x: number;
    y: number;
  };
  data: OrgMemberNodeData & Record<string, unknown>;
  width: number;
  height: number;
}

export interface OrgMemberEdge {
  id: string;
  source: string;
  target: string;
  type?: string;
  animated?: boolean;
}

// Message types
export interface Message {
  id: string;
  channel_id: string;
  sender_id: string;
  body: string;
  created_at: string;
  updated_at: string;
}

// Export for use in other files
export type { Database };