name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    strategy:
      matrix:
        node-version: [22.x]

    name: Create a Changesets release PR or GitHub release
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'imbhargav5/nextbase-nextjs-supabase-starter' }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🚂 CI Setup
        uses: ./.github/actions/ci-setup

      - name: Create release PR or GitHub release
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm release:github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
